with-expecter: true
disable-version-string: True
packages:
  github.com/JoshuaPangaribuan/billing-engine/internal/billing-engine:
    config:
      all: True
      recursive: True
      outpkg: "billingenginemocks"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/billing-engine/internal/mocks

  github.com/JoshuaPangaribuan/billing-engine/internal/pkg:
    config:
      all: True
      recursive: True
      outpkg: "pkgmocks"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/pkg/pkgmocks
