// Code generated by mockery. DO NOT EDIT.

package billingenginemocks

import (
	context "context"

	usecases "github.com/JoshuaPangaribuan/billing-engine/internal/billing-engine/internal/usecases"
	mock "github.com/stretchr/testify/mock"
)

// MockGetInstallmentsByLoanUsecase is an autogenerated mock type for the GetInstallmentsByLoanUsecase type
type MockGetInstallmentsByLoanUsecase struct {
	mock.Mock
}

type MockGetInstallmentsByLoanUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetInstallmentsByLoanUsecase) EXPECT() *MockGetInstallmentsByLoanUsecase_Expecter {
	return &MockGetInstallmentsByLoanUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, loanID
func (_m *MockGetInstallmentsByLoanUsecase) Execute(ctx context.Context, loanID uint64) ([]usecases.GetInstallmentsOutput, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []usecases.GetInstallmentsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]usecases.GetInstallmentsOutput, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []usecases.GetInstallmentsOutput); ok {
		r0 = rf(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecases.GetInstallmentsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetInstallmentsByLoanUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetInstallmentsByLoanUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID uint64
func (_e *MockGetInstallmentsByLoanUsecase_Expecter) Execute(ctx interface{}, loanID interface{}) *MockGetInstallmentsByLoanUsecase_Execute_Call {
	return &MockGetInstallmentsByLoanUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, loanID)}
}

func (_c *MockGetInstallmentsByLoanUsecase_Execute_Call) Run(run func(ctx context.Context, loanID uint64)) *MockGetInstallmentsByLoanUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockGetInstallmentsByLoanUsecase_Execute_Call) Return(_a0 []usecases.GetInstallmentsOutput, _a1 error) *MockGetInstallmentsByLoanUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetInstallmentsByLoanUsecase_Execute_Call) RunAndReturn(run func(context.Context, uint64) ([]usecases.GetInstallmentsOutput, error)) *MockGetInstallmentsByLoanUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetInstallmentsByLoanUsecase creates a new instance of MockGetInstallmentsByLoanUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetInstallmentsByLoanUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetInstallmentsByLoanUsecase {
	mock := &MockGetInstallmentsByLoanUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
