// Code generated by mockery. DO NOT EDIT.

package billingenginemocks

import (
	context "context"

	usecases "github.com/JoshuaPangaribuan/billing-engine/internal/billing-engine/internal/usecases"
	mock "github.com/stretchr/testify/mock"
)

// MockIsDelinquentUsecase is an autogenerated mock type for the IsDelinquentUsecase type
type MockIsDelinquentUsecase struct {
	mock.Mock
}

type MockIsDelinquentUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIsDelinquentUsecase) EXPECT() *MockIsDelinquentUsecase_Expecter {
	return &MockIsDelinquentUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, loanID
func (_m *MockIsDelinquentUsecase) Execute(ctx context.Context, loanID uint64) (usecases.IsDelinquentOutput, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.IsDelinquentOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (usecases.IsDelinquentOutput, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) usecases.IsDelinquentOutput); ok {
		r0 = rf(ctx, loanID)
	} else {
		r0 = ret.Get(0).(usecases.IsDelinquentOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIsDelinquentUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockIsDelinquentUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID uint64
func (_e *MockIsDelinquentUsecase_Expecter) Execute(ctx interface{}, loanID interface{}) *MockIsDelinquentUsecase_Execute_Call {
	return &MockIsDelinquentUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, loanID)}
}

func (_c *MockIsDelinquentUsecase_Execute_Call) Run(run func(ctx context.Context, loanID uint64)) *MockIsDelinquentUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockIsDelinquentUsecase_Execute_Call) Return(_a0 usecases.IsDelinquentOutput, _a1 error) *MockIsDelinquentUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIsDelinquentUsecase_Execute_Call) RunAndReturn(run func(context.Context, uint64) (usecases.IsDelinquentOutput, error)) *MockIsDelinquentUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIsDelinquentUsecase creates a new instance of MockIsDelinquentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIsDelinquentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIsDelinquentUsecase {
	mock := &MockIsDelinquentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
