// Code generated by mockery. DO NOT EDIT.

package billingenginemocks

import (
	context "context"

	usecases "github.com/JoshuaPangaribuan/billing-engine/internal/billing-engine/internal/usecases"
	mock "github.com/stretchr/testify/mock"
)

// MockGetAllCustomerUsecase is an autogenerated mock type for the GetAllCustomerUsecase type
type MockGetAllCustomerUsecase struct {
	mock.Mock
}

type MockGetAllCustomerUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetAllCustomerUsecase) EXPECT() *MockGetAllCustomerUsecase_Expecter {
	return &MockGetAllCustomerUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockGetAllCustomerUsecase) Execute(ctx context.Context) (usecases.GetAllCustomerOutput, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.GetAllCustomerOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (usecases.GetAllCustomerOutput, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) usecases.GetAllCustomerOutput); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(usecases.GetAllCustomerOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetAllCustomerUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetAllCustomerUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGetAllCustomerUsecase_Expecter) Execute(ctx interface{}) *MockGetAllCustomerUsecase_Execute_Call {
	return &MockGetAllCustomerUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockGetAllCustomerUsecase_Execute_Call) Run(run func(ctx context.Context)) *MockGetAllCustomerUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGetAllCustomerUsecase_Execute_Call) Return(_a0 usecases.GetAllCustomerOutput, _a1 error) *MockGetAllCustomerUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetAllCustomerUsecase_Execute_Call) RunAndReturn(run func(context.Context) (usecases.GetAllCustomerOutput, error)) *MockGetAllCustomerUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetAllCustomerUsecase creates a new instance of MockGetAllCustomerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetAllCustomerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetAllCustomerUsecase {
	mock := &MockGetAllCustomerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
