// Code generated by mockery. DO NOT EDIT.

package billingenginemocks

import (
	context "context"

	entity "github.com/JoshuaPangaribuan/billing-engine/internal/billing-engine/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockGetAllCustomerRepository is an autogenerated mock type for the GetAllCustomerRepository type
type MockGetAllCustomerRepository struct {
	mock.Mock
}

type MockGetAllCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetAllCustomerRepository) EXPECT() *MockGetAllCustomerRepository_Expecter {
	return &MockGetAllCustomerRepository_Expecter{mock: &_m.Mock}
}

// GetAllCustomer provides a mock function with given fields: ctx
func (_m *MockGetAllCustomerRepository) GetAllCustomer(ctx context.Context) ([]entity.Customer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCustomer")
	}

	var r0 []entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Customer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Customer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetAllCustomerRepository_GetAllCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCustomer'
type MockGetAllCustomerRepository_GetAllCustomer_Call struct {
	*mock.Call
}

// GetAllCustomer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGetAllCustomerRepository_Expecter) GetAllCustomer(ctx interface{}) *MockGetAllCustomerRepository_GetAllCustomer_Call {
	return &MockGetAllCustomerRepository_GetAllCustomer_Call{Call: _e.mock.On("GetAllCustomer", ctx)}
}

func (_c *MockGetAllCustomerRepository_GetAllCustomer_Call) Run(run func(ctx context.Context)) *MockGetAllCustomerRepository_GetAllCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGetAllCustomerRepository_GetAllCustomer_Call) Return(_a0 []entity.Customer, _a1 error) *MockGetAllCustomerRepository_GetAllCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetAllCustomerRepository_GetAllCustomer_Call) RunAndReturn(run func(context.Context) ([]entity.Customer, error)) *MockGetAllCustomerRepository_GetAllCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetAllCustomerRepository creates a new instance of MockGetAllCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetAllCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetAllCustomerRepository {
	mock := &MockGetAllCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
