// Code generated by mockery. DO NOT EDIT.

package billingenginemocks

import (
	context "context"

	usecases "github.com/JoshuaPangaribuan/billing-engine/internal/billing-engine/internal/usecases"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateCustomerUsecase is an autogenerated mock type for the CreateCustomerUsecase type
type MockCreateCustomerUsecase struct {
	mock.Mock
}

type MockCreateCustomerUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateCustomerUsecase) EXPECT() *MockCreateCustomerUsecase_Expecter {
	return &MockCreateCustomerUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockCreateCustomerUsecase) Execute(ctx context.Context, input usecases.CreateCustomerInput) (usecases.CreateCustomerOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 usecases.CreateCustomerOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecases.CreateCustomerInput) (usecases.CreateCustomerOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecases.CreateCustomerInput) usecases.CreateCustomerOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(usecases.CreateCustomerOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecases.CreateCustomerInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateCustomerUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateCustomerUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecases.CreateCustomerInput
func (_e *MockCreateCustomerUsecase_Expecter) Execute(ctx interface{}, input interface{}) *MockCreateCustomerUsecase_Execute_Call {
	return &MockCreateCustomerUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockCreateCustomerUsecase_Execute_Call) Run(run func(ctx context.Context, input usecases.CreateCustomerInput)) *MockCreateCustomerUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecases.CreateCustomerInput))
	})
	return _c
}

func (_c *MockCreateCustomerUsecase_Execute_Call) Return(_a0 usecases.CreateCustomerOutput, _a1 error) *MockCreateCustomerUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateCustomerUsecase_Execute_Call) RunAndReturn(run func(context.Context, usecases.CreateCustomerInput) (usecases.CreateCustomerOutput, error)) *MockCreateCustomerUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateCustomerUsecase creates a new instance of MockCreateCustomerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateCustomerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateCustomerUsecase {
	mock := &MockCreateCustomerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
