// Code generated by mockery. DO NOT EDIT.

package billingenginemocks

import (
	context "context"

	entity "github.com/JoshuaPangaribuan/billing-engine/internal/billing-engine/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockGetInstallmentsRepository is an autogenerated mock type for the GetInstallmentsRepository type
type MockGetInstallmentsRepository struct {
	mock.Mock
}

type MockGetInstallmentsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetInstallmentsRepository) EXPECT() *MockGetInstallmentsRepository_Expecter {
	return &MockGetInstallmentsRepository_Expecter{mock: &_m.Mock}
}

// GetInstallments provides a mock function with given fields: ctx, loanID
func (_m *MockGetInstallmentsRepository) GetInstallments(ctx context.Context, loanID uint64) ([]entity.Installment, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetInstallments")
	}

	var r0 []entity.Installment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]entity.Installment, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []entity.Installment); ok {
		r0 = rf(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Installment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetInstallmentsRepository_GetInstallments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallments'
type MockGetInstallmentsRepository_GetInstallments_Call struct {
	*mock.Call
}

// GetInstallments is a helper method to define mock.On call
//   - ctx context.Context
//   - loanID uint64
func (_e *MockGetInstallmentsRepository_Expecter) GetInstallments(ctx interface{}, loanID interface{}) *MockGetInstallmentsRepository_GetInstallments_Call {
	return &MockGetInstallmentsRepository_GetInstallments_Call{Call: _e.mock.On("GetInstallments", ctx, loanID)}
}

func (_c *MockGetInstallmentsRepository_GetInstallments_Call) Run(run func(ctx context.Context, loanID uint64)) *MockGetInstallmentsRepository_GetInstallments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockGetInstallmentsRepository_GetInstallments_Call) Return(_a0 []entity.Installment, _a1 error) *MockGetInstallmentsRepository_GetInstallments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetInstallmentsRepository_GetInstallments_Call) RunAndReturn(run func(context.Context, uint64) ([]entity.Installment, error)) *MockGetInstallmentsRepository_GetInstallments_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetInstallmentsRepository creates a new instance of MockGetInstallmentsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetInstallmentsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetInstallmentsRepository {
	mock := &MockGetInstallmentsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
